spring:

  application:
    name: Test12



  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Balonka888!

  liquibase:
    change-log: classpath:db/changelog/v1/changelog-master.xml


  jpa:
    hibernate:
      ddl-auto: validate